### ISSUE TITLE
Add support for bitmap (BMP) images

### ISSUE THREAD

**Issue by nikmauro** [claviska/SimpleImage#171]
```PHP

array(1) { ["path"]=> string(89) "public/media/upload-files/2017/02/strawberries.bmp" }
E_ERROR [#1]: Uncaught Exception: Unsupported image: public/media/upload-files/2017/02/strawberries.bmp in vendor/claviska/simpleimage/src/claviska/SimpleImage.php:159 Stack trace: #0 vendor/claviska/simpleimage/src/claviska/SimpleImage.php(57): claviska\SimpleImage->fromFile('/var/www/vhosts...') #1/library/cms39_media.php(647): claviska\SimpleImage->__construct('/var/www/vhosts...') #2 /library/cms39_media.php(121): resizePhoto(Array) #3 /library/cms39_template.php(332): processImage('2017/02/strawbe...', Array) #4 /library/plugin.php(202): meta_og_image('') #5 /library/cms39_template.php(350): apply_filters('og_image', '') #6 /public/themes/default/header.php(25): meta_og_data() # in vendor/claviska/simpleimage/src/claviska/SimpleImage.php:159

```

here is the bmp file https://we.tl/4j5vpzud3A

**Comment by claviska** [comment]
Bitmap images are not supported. Per the readme:

> Supports reading, writing, and converting GIF, JPEG, PNG, WEBP formats.

However, it looks like PHP 7.2 introduced [`imagecreatefrombmp`](http://php.net/manual/en/function.imagecreatefrombmp.php) and [`imagebmp`](http://php.net/manual/en/function.imagebmp.php) so we can probably add support now. A PR for this should be trivial.

If you'd like to submit one, that would be awesome. If not, I'll leave this open until I can get around to it. Here's what I believe needs to be done:

- [ ] Add BMP support to `fromFile` method
- [ ] Add BMP support to `generate` method
- [ ] Update readme to reflect BMP support

**Comment by nikmauro** [comment]
Take a look in this functions 
```PHP
/**
 * Creates function imagecreatefrombmp, since PHP doesn't have one
 * @return resource An image identifier, similar to imagecreatefrompng
 * @param string $filename Path to the BMP image
 * @see imagecreatefrompng
 * @author Glen Solsberry <glens@networldalliance.com>
 */
if (!function_exists("imagecreatefrombmp")) {
	function imagecreatefrombmp( $filename ) {
		$file = fopen( $filename, "rb" );
		$read = fread( $file, 10 );
		while( !feof( $file ) && $read != "" )
		{
			$read .= fread( $file, 1024 );
		}
		$temp = unpack( "H*", $read );
		$hex = $temp[1];
		$header = substr( $hex, 0, 104 );
		$body = str_split( substr( $hex, 108 ), 6 );
		if( substr( $header, 0, 4 ) == "424d" )
		{
			$header = substr( $header, 4 );
			// Remove some stuff?
			$header = substr( $header, 32 );
			// Get the width
			$width = hexdec( substr( $header, 0, 2 ) );
			// Remove some stuff?
			$header = substr( $header, 8 );
			// Get the height
			$height = hexdec( substr( $header, 0, 2 ) );
			unset( $header );
		}
		$x = 0;
		$y = 1;
		$image = imagecreatetruecolor( $width, $height );
		foreach( $body as $rgb )
		{
			$r = hexdec( substr( $rgb, 4, 2 ) );
			$g = hexdec( substr( $rgb, 2, 2 ) );
			$b = hexdec( substr( $rgb, 0, 2 ) );
			$color = imagecolorallocate( $image, $r, $g, $b );
			imagesetpixel( $image, $x, $height-$y, $color );
			$x++;
			if( $x >= $width )
			{
				$x = 0;
				$y++;
			}
		}
		return $image;
	}
}
```

or 

```PHP
//------------------------------------------------------------------------------
// suporte para a manipulação de arquivos BMP
/*********************************************/
/* Function: ImageCreateFromBMP              */
/* Author:   DHKold                          */
/* Contact:  admin@dhkold.com                */
/* Date:     The 15th of June 2005           */
/* Version:  2.0B                            */
/*********************************************/
function imagecreatefrombmp($filename) {
 //Ouverture du fichier en mode binaire
   if (! $f1 = fopen($filename,"rb")) return FALSE;
 //1 : Chargement des ent?tes FICHIER
   $FILE = unpack("vfile_type/Vfile_size/Vreserved/Vbitmap_offset", fread($f1,14));
   if ($FILE['file_type'] != 19778) return FALSE;
 //2 : Chargement des ent?tes BMP
   $BMP = unpack('Vheader_size/Vwidth/Vheight/vplanes/vbits_per_pixel'.
                     '/Vcompression/Vsize_bitmap/Vhoriz_resolution'.
                     '/Vvert_resolution/Vcolors_used/Vcolors_important', fread($f1,40));
   $BMP['colors'] = pow(2,$BMP['bits_per_pixel']);
   if ($BMP['size_bitmap'] == 0) $BMP['size_bitmap'] = $FILE['file_size'] - $FILE['bitmap_offset'];
   $BMP['bytes_per_pixel'] = $BMP['bits_per_pixel']/8;
   $BMP['bytes_per_pixel2'] = ceil($BMP['bytes_per_pixel']);
   $BMP['decal'] = ($BMP['width']*$BMP['bytes_per_pixel']/4);
   $BMP['decal'] -= floor($BMP['width']*$BMP['bytes_per_pixel']/4);
   $BMP['decal'] = 4-(4*$BMP['decal']);
   if ($BMP['decal'] == 4) $BMP['decal'] = 0;
 //3 : Chargement des couleurs de la palette
   $PALETTE = array();
   if ($BMP['colors'] < 16777216)
   {
     $PALETTE = unpack('V'.$BMP['colors'], fread($f1,$BMP['colors']*4));
   }
 //4 : Cr?ation de l'image
   $IMG = fread($f1,$BMP['size_bitmap']);
   $VIDE = chr(0);
   $res = imagecreatetruecolor($BMP['width'],$BMP['height']);
   $P = 0;
   $Y = $BMP['height']-1;
   while ($Y >= 0)
   {
     $X=0;
     while ($X < $BMP['width'])
     {
      if ($BMP['bits_per_pixel'] == 24)
          $COLOR = @unpack("V",substr($IMG,$P,3).$VIDE);
      elseif ($BMP['bits_per_pixel'] == 16)
      {
          $COLOR = @unpack("n",substr($IMG,$P,2));
          $COLOR[1] = $PALETTE[$COLOR[1]+1];
      }
      elseif ($BMP['bits_per_pixel'] == 8)
      {
          $COLOR = @unpack("n",$VIDE.substr($IMG,$P,1));
          $COLOR[1] = $PALETTE[$COLOR[1]+1];
      }
      elseif ($BMP['bits_per_pixel'] == 4)
      {
          $COLOR = @unpack("n",$VIDE.substr($IMG,floor($P),1));
          if (($P*2)%2 == 0) $COLOR[1] = ($COLOR[1] >> 4) ; else $COLOR[1] = ($COLOR[1] & 0x0F);
          $COLOR[1] = $PALETTE[$COLOR[1]+1];
      }
      elseif ($BMP['bits_per_pixel'] == 1)
      {
          $COLOR = @unpack("n",$VIDE.substr($IMG,floor($P),1));
          if     (($P*8)%8 == 0) $COLOR[1] =  $COLOR[1]          >>7;
          elseif (($P*8)%8 == 1) $COLOR[1] = ($COLOR[1] & 0x40)>>6;
          elseif (($P*8)%8 == 2) $COLOR[1] = ($COLOR[1] & 0x20)>>5;
          elseif (($P*8)%8 == 3) $COLOR[1] = ($COLOR[1] & 0x10)>>4;
          elseif (($P*8)%8 == 4) $COLOR[1] = ($COLOR[1] & 0x8)>>3;
          elseif (($P*8)%8 == 5) $COLOR[1] = ($COLOR[1] & 0x4)>>2;
          elseif (($P*8)%8 == 6) $COLOR[1] = ($COLOR[1] & 0x2)>>1;
          elseif (($P*8)%8 == 7) $COLOR[1] = ($COLOR[1] & 0x1);
          $COLOR[1] = $PALETTE[$COLOR[1]+1];
      }
      else
          return FALSE;
      imagesetpixel($res,$X,$Y,$COLOR[1]);
      $X++;
      $P += $BMP['bytes_per_pixel'];
     }
     $Y--;
     $P+=$BMP['decal'];
   }
 //Fermeture du fichier
   fclose($f1);
 return $res;
} // fim function image from BMP
``

**Comment by nikmauro** [comment]
this function not working with BMP http://php.net/manual/en/function.imagecreatefromwbmp.php

**Comment by claviska** [comment]
[`imagecreatefromwbmp`](http://php.net/manual/en/function.imagecreatefromwbmp.php) is not intended to work with Bitmaps (despite the similarity, WBMP is a different format than BMP).

I'd prefer not to use the methods you posted, as Bitmap support has never been requested before and they would add a considerable amount of extra code to the library. I'm not even sure if the license is compatible.

Since PHP 7.2 has [imagecreatefrombmp](http://php.net/manual/en/function.imagecreatefrombmp.php) and [imagebmp](http://php.net/manual/en/function.imagebmp.php) built in, I'm OK with requiring that version for this particular feature. Using the built-in methods will only require a few lines of code.

If you need support for PHP < 7.2 (which is understandable), I'd suggest converting the images before using them with SimpleImage.

**Comment by nikmauro** [comment]
I agree for php 7 implementation!

**Comment by shadowjohn** [comment]
DHKold version works like a charm.
